<a href="https://colab.research.google.com/github/Shubham-Das-Coder/Machine_Learning_Course_With_Python/blob/main/Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importing the libraries
import numpy as np

In [2]:
#Creating a matrix using numpy
matrix_1=np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [3]:
#Displaying the shape of the matrix
matrix_1.shape

(2, 2)

In [4]:
#Creating a matrix using numpy
matrix_2=np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [5]:
#Displaying the shape of the matrix
matrix_2.shape

(3, 3)

In [6]:
#Creating matrices with random floating values
random_matrix=np.random.rand(3,3)
print(random_matrix)

[[0.32198576 0.19881617 0.73585813]
 [0.94116712 0.38529217 0.51295207]
 [0.34877718 0.73586163 0.58329141]]


In [7]:
#Creating matrices with random integer values
random_integer_matrix=np.random.randint(100,size=(4,4))
print(random_integer_matrix)

[[86 17 71  4]
 [93 30 86 55]
 [55  2 50 50]
 [54 34  8 74]]


In [8]:
#Matrix with all the values as 1
matrix_with_ones=np.ones((3,4))
print(matrix_with_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
#Matrix with all the values as 1
matrix_with_ones_2=np.ones((4,3),dtype=int)
print(matrix_with_ones_2)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [10]:
#Null matrix or zero matrix
null_matrix=np.zeros((5,5))
print(null_matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
#Identity matrix
identity_matrix=np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
#Transpose of a matrix
a=np.random.randint(100,size=(4,4))
print(a)
transpose_of_a=np.transpose(a)
print(transpose_of_a)

[[56 23 40 90]
 [47 29 33 38]
 [84 33 98 64]
 [49 36 65 29]]
[[56 47 84 49]
 [23 29 33 36]
 [40 33 98 65]
 [90 38 64 29]]


In [13]:
#Transpose of a matrix
b=np.random.randint(100,size=(3,4))
print(b)
transpose_of_b=np.transpose(b)
print(transpose_of_b)

[[92 36 40 60]
 [16 70 17 94]
 [42 76 74 83]]
[[92 16 42]
 [36 70 76]
 [40 17 74]
 [60 94 83]]


In [14]:
#Addition of matrices
A=np.array([[2,3],[4,5]])
print(A)
B=np.array([[6,7],[8,9]])
print(B)

[[2 3]
 [4 5]]
[[6 7]
 [8 9]]


In [15]:
A.shape
B.shape

(2, 2)

In [16]:
sum=A+B
print(sum)

[[ 8 10]
 [12 14]]


In [17]:
#Creating two matrices with random values
matrix_1=np.random.randint(10,size=(3,3))
matrix_2=np.random.randint(10,size=(3,3))

In [18]:
print(matrix_1)

[[6 4 9]
 [8 4 9]
 [6 5 0]]


In [19]:
print(matrix_2)

[[5 5 5]
 [8 2 3]
 [6 3 5]]


In [20]:
sum=np.add(matrix_1,matrix_2)
print(sum)

[[11  9 14]
 [16  6 12]
 [12  8  5]]


In [21]:
#Subtraction of two matrices
A=np.array([[5,6],[7,8]])
B=np.array([[1,2],[3,4]])
print(A)
print(B)

[[5 6]
 [7 8]]
[[1 2]
 [3 4]]


In [22]:
difference=A-B
print(difference)

[[4 4]
 [4 4]]


In [23]:
#Creating two matrices with random values
matrix1=np.random.randint(10,size=(3,3))
matrix2=np.random.randint(10,size=(3,3))

In [24]:
print(matrix1)
print(matrix2)

[[6 6 3]
 [2 8 0]
 [9 3 0]]
[[9 0 9]
 [4 3 0]
 [0 4 4]]


In [25]:
diff=np.subtract(matrix1,matrix2)
print(diff)

[[-3  6 -6]
 [-2  5  0]
 [ 9 -1 -4]]


In [26]:
#Multiplying a matrix by a scalar
x=5
y=np.random.randint(10,size=(4,4))
print(y)

[[7 6 2 5]
 [0 8 9 6]
 [5 5 5 9]
 [4 1 0 6]]


In [27]:
product=np.multiply(x,y)
print(product)

[[35 30 10 25]
 [ 0 40 45 30]
 [25 25 25 45]
 [20  5  0 30]]


In [28]:
#Multiplying 2 matrices
Matrix_1=np.random.randint(5,size=(3,3))
Matrix_2=np.random.randint(5,size=(3,4))
print(Matrix_1)
print(Matrix_2)

[[3 4 2]
 [4 3 4]
 [1 3 0]]
[[0 4 1 3]
 [0 2 0 0]
 [4 2 0 1]]


In [29]:
prod=np.dot(Matrix_1,Matrix_2)
print(prod)

[[ 8 24  3 11]
 [16 30  4 16]
 [ 0 10  1  3]]


In [30]:
prod.shape

(3, 4)

In [31]:
#Multiplying 2 matrices
Matrix_1=np.random.randint(5,size=(3,3))
Matrix_2=np.random.randint(5,size=(3,3))
print(Matrix_1)
print(Matrix_2)

[[0 4 3]
 [3 2 1]
 [3 3 4]]
[[3 3 0]
 [0 2 4]
 [1 2 3]]


In [32]:
prod=np.dot(Matrix_1,Matrix_2)
print(prod)

[[ 3 14 25]
 [10 15 11]
 [13 23 24]]


In [33]:
prod.shape

(3, 3)

In [34]:
mat_1=np.random.randint(5,size=(3,3))
mat_2=np.random.randint(5,size=(3,3))
print(mat_1)
print(mat_2)

[[3 4 4]
 [0 3 3]
 [1 2 2]]
[[4 4 3]
 [3 4 0]
 [4 0 4]]


In [35]:
mult=np.multiply(mat_1,mat_2)
print(mult)

[[12 16 12]
 [ 0 12  0]
 [ 4  0  8]]


In [36]:
mult.shape

(3, 3)