<a href="https://colab.research.google.com/github/Shubham-Das-Coder/Machine_Learning_Course_With_Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#***Importing Library***

In [1]:
import numpy as np

#***List Vs Numpy - Time Taken***

In [2]:
from time import process_time

#***Time Taken By A List***

In [3]:
python_list=[i for i in range(10000)]

start_time=process_time()

python_list=[i+5 for i in python_list]

end_time=process_time()

print(end_time-start_time)

0.001596702000000061


In [4]:
np_array=np.array([i for i in range(10000)])

start_time=process_time()

np_array+=5

end_time=process_time()

print(end_time-start_time)

0.0002650179999998947


#***Numpy Arrays***

In [5]:
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [6]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [7]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
a.shape

(4,)

In [9]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
b.shape

(2, 4)

In [11]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


#***Initial Placeholders In Numpy Arrays***

In [12]:
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [15]:
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
b=np.random.random((3,4))
print(b)

[[0.48163303 0.5698089  0.60876792 0.46240238]
 [0.04889382 0.55542147 0.66562837 0.46969173]
 [0.71940142 0.59402352 0.89778889 0.809793  ]]


In [17]:
c=np.random.randint(10,100,(3,5))
print(c)

[[38 56 17 60 62]
 [15 18 47 55 83]
 [94 90 74 61 27]]


In [18]:
d=np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [19]:
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


In [20]:
list2=[10,20,30,40,50]

np_array=np.array(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

In [21]:
c=np.random.randint(10,90,(5,5))
print(c)

[[12 44 44 50 30]
 [46 35 64 64 20]
 [29 29 66 17 36]
 [21 24 68 24 32]
 [70 84 57 76 78]]


In [22]:
print(c.shape)

(5, 5)


In [23]:
print(c.ndim)

2


In [24]:
print(c.size)

25


In [25]:
print(c.dtype)

int64


#***Mathematical Operations On A Numpy Array***

In [26]:
list1=[1,3,5,7,9]
list2=[2,4,6,8]
print(list1+list2)

[1, 3, 5, 7, 9, 2, 4, 6, 8]


In [27]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[7 4 7]
 [4 5 6]
 [3 6 2]]
[[18 16 16]
 [19 14 19]
 [13 14 10]]


In [28]:
print(a+b)

[[25 20 23]
 [23 19 25]
 [16 20 12]]


In [29]:
print(a-b)

[[-11 -12  -9]
 [-15  -9 -13]
 [-10  -8  -8]]


In [30]:
print(a*b)

[[126  64 112]
 [ 76  70 114]
 [ 39  84  20]]


In [31]:
print(a/b)

[[0.38888889 0.25       0.4375    ]
 [0.21052632 0.35714286 0.31578947]
 [0.23076923 0.42857143 0.2       ]]


In [32]:
c=np.random.randint(0,10,(3,3))
d=np.random.randint(10,20,(3,3))
print(c)
print(d)

[[3 5 4]
 [2 7 9]
 [0 0 7]]
[[16 10 14]
 [11 14 19]
 [16 12 19]]


In [33]:
print(np.add(c,d))

[[19 15 18]
 [13 21 28]
 [16 12 26]]


In [34]:
print(np.subtract(c,d))

[[-13  -5 -10]
 [ -9  -7 -10]
 [-16 -12 -12]]


In [35]:
print(np.multiply(c,d))

[[ 48  50  56]
 [ 22  98 171]
 [  0   0 133]]


In [36]:
print(np.divide(c,d))

[[0.1875     0.5        0.28571429]
 [0.18181818 0.5        0.47368421]
 [0.         0.         0.36842105]]


*Array Manipulation*

In [37]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 1 0]
 [8 8 2]]
(2, 3)


In [38]:
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[4 8]
 [1 8]
 [0 2]]
(3, 2)


In [39]:
trans2=array.T
print(trans2)
print(trans2.shape)

[[4 8]
 [1 8]
 [0 2]]
(3, 2)


In [40]:
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[6 0 9]
 [8 5 8]]
(2, 3)


In [41]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[6 0]
 [9 8]
 [5 8]]
(3, 2)
